config/routes.rb
Rails.application.routes.draw do
  root :to => 'products#index'
  resources :products do
    resources :reviews, :only => [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  validates :name,:cost,:country, :presence => true
  validates_numericality_of :cost

  scope :most_reviewed_products, -> {(
    select("products.id, products.name, products.cost, products.country,count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(3)
  )}

  scope :recently_added_products, -> {
    order(created_at: :desc).limit(3)
  }

  scope :local_products, -> {
    where("country like ?", "USA")
  }
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  validates :author, :presence => true
  validates :rating, :presence => true
  validates :content, :presence =>true, :length => {:minimum =>50, :maximum => 250}
  validates_inclusion_of :rating, :in => 1..5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    # @products = Product.all
    @products = Product.paginate(:page => params[:page], :per_page => 5)
    @most_reviewed_products = Product.most_reviewed_products
    @local_products = Product.local_products.paginate(:page => params[:local_page], :per_page => 3)
    @recently_added_products = Product.recently_added_products.paginate(:page => params[:recent_page], :per_page => 3)
  end

  def edit
    @product = Product.find(params[:id])
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "New product added successfully!"
      redirect_to  product_path(@product)
    else
      render :new
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product updated successfully!"
      redirect_to  product_path(@product)
    else
      render :edit
    end
  end

private

  def product_params
    params.require(:product).permit(:name,:cost,:country)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review added successfully!"
      redirect_to product_path(@review.product)
    else
      render :new
    end
  end

private
  def review_params
    params.require(:review).permit(:author,:content,:rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarioFoods</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top navbar-bg-color">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Mario's food</a>

        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active-bg"><a href="/">Home</a></li>
            <li><a href="/products/new">Add new product</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav><br><br><br><br>
    <div class="container">
      <%= flash[:notice] %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_display_products.html.erb
<% if products.any?() %>
  <% products.each do |product| %>
    <div class="card well well-bg">
      <div class="card-block">
        <h4 class="card-title"><%= product.name %></h4>
        <p class="card-text">
          $<%= product.cost %>
        </p>
        <p><%= link_to "See details and reviews", product_path(product) %></p>
      </div>
    </div>
  <% end %>
<% else %>
  <h4>No products Yet</h4>
<% end %>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :cost %><br>
  <%= f.text_field :cost %><br>
  <%= f.label :country %><br>
  <%= f.text_field :country %><br><br>
  <%= f.submit 'Submit', :class => 'btn btn-primary' %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form" %>

app/views/products/index.html.erb
<h1>Welcome to Mario's Speciality Food Products</h1>
<% content_for(:title, "Welcome") %>
<div class="jumbotron">
  <div class="row">
    <div class="col-md-4">
      <h3 class="row">Most reviewed products</h3>
      <%= render "display_products", :products => @most_reviewed_products %>
    </div>
    <div class="col-md-4">
      <h3 class="row">Local products</h3>
      <%= render "display_products", :products => @local_products %>
      <%= will_paginate @local_products, :param_name => 'local_page', renderer: BootstrapPagination::Rails %>
    </div>
    <div class="col-md-4">
      <h3 class="row">Recently added products</h3>
      <%= render "display_products", :products => @recently_added_products %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h3 class="row">All products</h3>
      <%= will_paginate @products , renderer: BootstrapPagination::Rails%>
      <%= render "display_products", :products => @products %>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form" %>

app/views/products/show.html.erb
<div class="jumbotron">
  <h2 class="product-header"> <%= @product.name %></h2>
  <h5>Price: $<%= @product.cost %></h5>
  <h5>Country: <%= @product.country %></h5>
  <h6>
    <%= link_to "Edit", edit_product_path(@product) %> &nbsp;
    <%= link_to "Delete", product_path(@product),                            :data => {:confirm => "Are you sure?",                                           :method => "delete"} %>
  </h6>
  <%= link_to "Add Review", new_product_review_path(@product)%>
</div>

<% if @product.reviews.any? %>
  <h4>Here are the reviews for this product:</h4>

  <ul>
    <% @product.reviews.each do |review| %>
    <div class="well">
      <div class="row review-header">
        <div class="col-md-4">
          <p><%= review.author %></p>
        </div>
        <div class="col-md-2">
          Rating: <%= review.rating %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p>
            <%= review.content %>
          </p>
        </div>
      </div>
    </div>
    <% end %>
  </ul>
<% else %>
  <p>There are no reviews yet!</p>
<% end %>

app/views/reviews/_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product,@review] do |f| %>
  <%= f.label :author %><br>
  <%= f.text_field :author %><br>
  <%= f.label :content %><br>
  <%= f.text_area :content %><br>
  <%= f.label :rating %><br>
  <%= f.text_field :rating %><br><br>
  <%= f.submit 'Submit', :class => 'btn btn-primary' %>
<% end %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render "form" %>

<!-- Product.select("products.name, products.cost, products.country, count(reviews.id) as reviews_count").joins(:reviews).group("products.id").order("reviews_count DESC").limit(5) -->